logging:
  level:
    ru.yandex.practicum: TRACE
    org:
      springframework: ERROR
      springframework.cloud.netflix.eureka: INFO
      apache.kafka: WARN

collector:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      properties:
        "bootstrap.servers": ${aggregator.kafka.bootstrap-servers:}
        "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
        "value.serializer": "ru.yandex.practicum.serializer.AvroSerializer"
        "telemetry.sensors.topic": "telemetry.sensors.v1"
        "telemetry.hubs.topic": "telemetry.hubs.v1"


  grpc:
    server:
      port: 9090
