logging:
  level:
    ru.yandex.practicum: TRACE
    org:
      springframework: ERROR
      springframework.cloud.netflix.eureka: INFO
      apache.kafka: WARN

analyzer:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      properties:
        "bootstrap.servers": ${aggregator.kafka.bootstrap-servers:}
        "enable.auto.commit": false
        "group-id.telemetry-snapshot": "telemetry.analyzer.snapshot"
        "group-id.telemetry-hub": "telemetry.analyzer.hub"
        "key.deserializer": "org.apache.kafka.common.serialization.StringDeserializer"
        "value.deserializer.snapshot": "ru.yandex.practicum.deserializer.SensorsSnapshotDeserializer"
        "value.deserializer.hub": "ru.yandex.practicum.deserializer.HubEventDeserializer"
        "telemetry.snapshots.topic": "telemetry.snapshots.v1"
        "telemetry.hubs.topic": "telemetry.hubs.v1"
      poll-timeout: 100ms

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/analyzer
    username: analyzer
    password: analyzer

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

grpc:
  client:
    hub-router:
      address: localhost:59090
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true